on:
  pull_request:
name: "py-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./

      - name: Make loadable
        run: |
          cd core
          make loadable

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: anaconda-client-env
          python-version: "3.10"

      - name: Install SQLite
        run: conda install sqlite

      - name: Check SQLite Version
        run: echo "import sqlite3; print(sqlite3.sqlite_version)" | python

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Test
        run: cd py/correctness && ./install-and-test.sh
